### ISSUE TITLE
**Скласти інтро**

### ISSUE THREAD

**Issue by Romazes** [Romazes/homepage#4]
Скласти інтро *(вступ)*, де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Dimonchik20** [comment]
**Are you seriously ? Why are you trouble me about such small things ?**

**Comment by Romazes** [comment]
I'm not a joke.
Plz, help me, understand basic with GitHub.
